.TH "PUBLIC" 3 "Version 0.0.4" "TrueRandom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PUBLIC \- API
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtruernd_is_supported\fP (void)"
.br
.RI "Check if hardware random number generation is supported\&. "
.ti -1c
.RI "NAKED uint32_t \fBtruernd_gen32\fP (void)"
.br
.RI "Generate a 32-bit true random number (single attempt)\&. "
.ti -1c
.RI "NAKED uint64_t \fBtruernd_gen64\fP (void)"
.br
.RI "Generate a 64-bit true random number (single attempt)\&. "
.ti -1c
.RI "NAKED int \fBtruernd_get32\fP (uint32_t *out)"
.br
.RI "Generate a 32-bit true random number (single attempt)\&. "
.ti -1c
.RI "NAKED int \fBtruernd_get64\fP (uint64_t *out)"
.br
.RI "Generate a 64-bit true random number (single attempt)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "NAKED uint32_t truernd_gen32 (void )"

.PP
Generate a 32-bit true random number (single attempt)\&. 
.PP
\fBReturns\fP
.RS 4
The random value 
.RE
.PP

.SS "NAKED uint64_t truernd_gen64 (void )"

.PP
Generate a 64-bit true random number (single attempt)\&. 
.PP
\fBReturns\fP
.RS 4
The random value 
.RE
.PP

.SS "NAKED int truernd_get32 (uint32_t * out)"

.PP
Generate a 32-bit true random number (single attempt)\&. 
.PP
\fBParameters\fP
.RS 4
\fIout\fP Pointer to store the random number 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SS "NAKED int truernd_get64 (uint64_t * out)"

.PP
Generate a 64-bit true random number (single attempt)\&. 
.PP
\fBParameters\fP
.RS 4
\fIout\fP Pointer to store the random number 
.RE
.PP
\fBReturns\fP
.RS 4
0 on success, -1 on failure 
.RE
.PP

.SS "int truernd_is_supported (void )"

.PP
Check if hardware random number generation is supported\&. 
.PP
\fBReturns\fP
.RS 4
1 if supported, 0 if not supported 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TrueRandom from the source code\&.
