.TH "test.c" 3 "Version 0.0.4" "TrueRandom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.c \- Comprehensive test suite for \fBtruerandom\&.h\fP library\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'truerandom\&.h'\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTRUERANDOM_IMPLEMENTATION\fP"
.br
.ti -1c
.RI "#define \fBTEST_ITERATIONS\fP   1000000"
.br
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   256"
.br
.ti -1c
.RI "#define \fBANSI_RESET\fP   '\\033[0m'"
.br
.ti -1c
.RI "#define \fBANSI_BOLD\fP   '\\033[1m'"
.br
.ti -1c
.RI "#define \fBANSI_DIM\fP   '\\033[2m'"
.br
.ti -1c
.RI "#define \fBANSI_RED\fP   '\\033[31m'"
.br
.ti -1c
.RI "#define \fBANSI_GREEN\fP   '\\033[32m'"
.br
.ti -1c
.RI "#define \fBANSI_YELLOW\fP   '\\033[33m'"
.br
.ti -1c
.RI "#define \fBANSI_BLUE\fP   '\\033[34m'"
.br
.ti -1c
.RI "#define \fBANSI_MAGENTA\fP   '\\033[35m'"
.br
.ti -1c
.RI "#define \fBANSI_CYAN\fP   '\\033[36m'"
.br
.ti -1c
.RI "#define \fBSYMBOL_PASS\fP   '✓'"
.br
.ti -1c
.RI "#define \fBSYMBOL_FAIL\fP   '✗'"
.br
.ti -1c
.RI "#define \fBSYMBOL_WARNING\fP   '⚠'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "Main test runner\&. "
.in -1c
.SH "Detailed Description"
.PP 
Comprehensive test suite for \fBtruerandom\&.h\fP library\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for TrueRandom from the source code\&.
